Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:service}-${opt:stage, self:provider.stage}-user-pool

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:service}-${opt:stage, self:provider.stage}-user-pool-client
      UserPoolId:
        Ref: CognitoUserPool
      GenerateSecret: true